name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump Version
        shell: bash
        run: |
          bump_type="${{ inputs.bump_type }}"

          version=$(jq -r .version package.json)
          IFS='.' read -r major minor patch <<< "$version"

          case $bump_type in
              major)
                major=$((major + 1))
                minor=0
                patch=0
              ;;

              minor)
                minor=$((minor + 1))
                patch=0
              ;;

              patch)
                patch=$((patch + 1))
              ;;

              *)
                echo "Unknown bump_type: $bump_type"
                exit 1
              ;;
          esac

          version="$major.$minor.$patch"
          echo "Bumping to $version"

          files=$(find . -type f -name package.json -prune)
          for file in $files; do
              echo "$(cat $file | jq ".version = \"$version\"" )" > $file
          done

          git config user.name "Sara Morillon"
          git config user.email "sara.morillon.pro@gmail.com"
          git commit -am "v$version"
          git tag -a "v$version"
          git push --follow-tags

  send_discord_notification:
    runs-on: ubuntu-latest

    needs: build_and_test

    if: always()

    steps:
      - name: Send Discord notification
        shell: bash
        run: |
          result="${{ needs.build_and_test.result }}"
          repo_url="[${{ github.repository }}](<https://github.com/${{ github.repository }}>)"
          curl -X POST -d "{\"content\":\"Checks on $repo_url: **${result^^}**\"}" -H "Content-Type: application/json" ${{ secrets.DISCORD_WEBHOOK }}
